[package]
name = "settings_json"
version = "0.30.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[lib]
path = "src/settings_json.rs"
doctest = false

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_json_lenient = "0.2"
serde_path_to_error = "0.1"
