[package]
name = "theme_settings"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[lib]
path = "src/theme_settings.rs"
doctest = false

[dependencies]
anyhow = "1"
gpui = { git = "https://github.com/zed-industries/zed", rev = "f66ed399cdde86092af8af3dc7b418abf45f37f8" }
serde = { version = "1", features = ["derive"] }
settings = { path = "../settings-stub" }
