[package]
name = "crossh-git-view"
version = "0.36.0"
edition = "2024"
license = "GPL-3.0-or-later"

[features]
visual-tests = []

[dependencies]
crossh-core = { path = "../crossh-core" }
crossh-editor = { path = "../crossh-editor" }
crossh-ui = { path = "../crossh-ui" }
crossh-ui-component = { path = "../crossh-ui-component" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "a84689073d296dfd39987bc7dd478e43ef76d83a" }
rust-i18n = "4"

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "a84689073d296dfd39987bc7dd478e43ef76d83a", features = ["test-support"] }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "a84689073d296dfd39987bc7dd478e43ef76d83a", features = ["font-kit", "test-support", "wayland", "x11"] }
