[package]
name = "crossh-ssh"
version = "0.14.2"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
anyhow = "1"
async-channel = "2"
crossh-core = { path = "../crossh-core" }
log = "0.4"
russh = "0.62"
russh-sftp = "2.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "sync", "io-util", "net", "time", "fs"] }

[dev-dependencies]
env_logger = "0.11"
