[package]
name = "settings"
version = "0.29.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[lib]
path = "src/settings.rs"
doctest = false

[dependencies]
anyhow = "1"
collections = { git = "https://github.com/zed-industries/zed", rev = "f66ed399cdde86092af8af3dc7b418abf45f37f8" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "f66ed399cdde86092af8af3dc7b418abf45f37f8" }
indexmap = { version = "2", features = ["serde"] }
inventory = "0.3"
parking_lot = "0.12"
schemars = "1"
serde = { version = "1", features = ["derive"] }
settings_macros = { git = "https://github.com/zed-industries/zed", rev = "f66ed399cdde86092af8af3dc7b418abf45f37f8" }
derive_more = { version = "1", features = ["from_str"] }
