[package]
name = "crossh-core"
version = "0.11.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
async-channel = "2"
base64 = "0.22"
dirs = "6"
libc = "0.2"
log = "0.4"
serde = { version = "1", features = ["derive"] }
tempfile = "3"
thiserror = "2"
toml = "0.8"

[dev-dependencies]
pretty_assertions = "1"
