[package]
name = "crossh-ui-component"
version = "0.19.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
crossh-ui = { path = "../crossh-ui" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "1b04e4caf01e376624fb514ef85b0e6d8ee5d930" }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "1b04e4caf01e376624fb514ef85b0e6d8ee5d930", features = ["test-support"] }
