[package]
name = "crossh-ui-component"
version = "0.36.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
crossh-ui-base = { path = "../crossh-ui-base" }
crossh-ui = { path = "../crossh-ui" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "a84689073d296dfd39987bc7dd478e43ef76d83a" }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "a84689073d296dfd39987bc7dd478e43ef76d83a", features = ["test-support"] }
