[package]
name = "crossh-ui-component"
version = "0.35.1"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
crossh-ui-base = { path = "../crossh-ui-base" }
crossh-ui = { path = "../crossh-ui" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "74646bf29c1a3d1cdb178930d810ecc5a8a6bece" }

[dev-dependencies]
gpui = { git = "https://github.com/zed-industries/zed", rev = "74646bf29c1a3d1cdb178930d810ecc5a8a6bece", features = ["test-support"] }
