[package]
name = "crossh-ui"
version = "0.35.1"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
assets = { git = "https://github.com/zed-industries/zed", rev = "74646bf29c1a3d1cdb178930d810ecc5a8a6bece" }
crossh-assets = { path = "../crossh-assets" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "74646bf29c1a3d1cdb178930d810ecc5a8a6bece" }
