[package]
name = "crossh-ui"
version = "0.22.1"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
assets = { git = "https://github.com/zed-industries/zed", rev = "1b04e4caf01e376624fb514ef85b0e6d8ee5d930" }
crossh-assets = { path = "../crossh-assets" }
crossh-theme = { path = "../crossh-theme" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "1b04e4caf01e376624fb514ef85b0e6d8ee5d930" }
